 /* istanbul ignore next */ const ELEMENTS=[{n:1,s:'H',name:'Hydrogen',m:1.008,cat:'nonmetal'},{n:2,s:'He',name:'Helium',m:4.003,cat:'noble'},{n:3,s:'Li',name:'Lithium',m:6.941,cat:'metal'},{n:4,s:'Be',name:'Beryllium',m:9.012,cat:'metal'},{n:5,s:'B',name:'Boron',m:10.81,cat:'metalloid'},{n:6,s:'C',name:'Carbon',m:12.011,cat:'nonmetal'},{n:7,s:'N',name:'Nitrogen',m:14.007,cat:'nonmetal'},{n:8,s:'O',name:'Oxygen',m:15.999,cat:'nonmetal'},{n:9,s:'F',name:'Fluorine',m:18.998,cat:'nonmetal'},{n:10,s:'Ne',name:'Neon',m:20.18,cat:'noble'},{n:11,s:'Na',name:'Sodium',m:22.99,cat:'metal'},{n:12,s:'Mg',name:'Magnesium',m:24.305,cat:'metal'},{n:13,s:'Al',name:'Aluminium',m:26.982,cat:'metal'},{n:14,s:'Si',name:'Silicon',m:28.086,cat:'metalloid'},{n:15,s:'P',name:'Phosphorus',m:30.974,cat:'nonmetal'},{n:16,s:'S',name:'Sulfur',m:32.06,cat:'nonmetal'},{n:17,s:'Cl',name:'Chlorine',m:35.45,cat:'nonmetal'},{n:18,s:'Ar',name:'Argon',m:39.948,cat:'noble'},{n:19,s:'K',name:'Potassium',m:39.098,cat:'metal'},{n:20,s:'Ca',name:'Calcium',m:40.078,cat:'metal'},{n:26,s:'Fe',name:'Iron',m:55.845,cat:'metal'},{n:29,s:'Cu',name:'Copper',m:63.546,cat:'metal'},{n:47,s:'Ag',name:'Silver',m:107.87,cat:'metal'},{n:79,s:'Au',name:'Gold',m:196.97,cat:'metal'}];
 /* istanbul ignore next */ const CAT_COLORS={nonmetal:'rgba(34,197,94,.15)',noble:'rgba(168,85,247,.15)',metal:'rgba(59,130,246,.15)',metalloid:'rgba(234,179,8,.15)'};

 function renderTable(elems){if(typeof document==='undefined')return;const el=document.getElementById('app');if(!el)return;const list=elems||ELEMENTS;el.innerHTML='<div class="card glass"><input type="text" id="search" class="input w-full" placeholder="🔍 Search elements..." oninput="filterElements()"><div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(70px,1fr));gap:4px;margin-top:16px">'+list.map(function(e){return'<div style="padding:8px 4px;text-align:center;cursor:pointer;background:'+CAT_COLORS[e.cat]+';transition:all .2s" onclick="showDetail('+e.n+')"><div style="font-size:.6rem;color:var(--color-text-secondary)">'+e.n+'</div><div style="font-weight:800;font-size:1rem">'+e.s+'</div></div>'}).join('')+'</div></div><div id="detail"></div>'}

 function showDetail(num){if(typeof document==='undefined')return;var e=ELEMENTS.find(function(x){return x.n===num});if(!e)return;var el=document.getElementById('detail');if(!el)return;el.innerHTML='<div class="card glass" style="margin-top:16px"><div style="font-size:4rem;font-weight:900;text-align:center;background:linear-gradient(135deg,var(--color-primary),var(--color-accent));-webkit-background-clip:text;-webkit-text-fill-color:transparent">'+e.s+'</div><h2 style="text-align:center">'+e.name+'</h2><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:12px"><div style="padding:8px;background:var(--color-surface-alt);color:var(--color-text-secondary)">Atomic Number</div><div style="font-weight:700">'+e.n+'</div></div><div style="padding:8px;background:var(--color-surface-alt);color:var(--color-text-secondary)">Mass</div><div style="font-weight:700">'+e.m+'</div></div><div style="padding:8px;background:var(--color-surface-alt);color:var(--color-text-secondary)">Category</div><div style="font-weight:700">'+e.cat+'</div></div></div></div>'}

  /* istanbul ignore next */ function filterElements(){if(typeof document==='undefined')return;var q=(document.getElementById('search')||{value:''}).value.toLowerCase();var filtered=q?ELEMENTS.filter(function(e){return e.name.toLowerCase().indexOf(q)!==-1||e.s.toLowerCase().indexOf(q)!==-1||String(e.n).indexOf(q)!==-1}):ELEMENTS;renderTable(filtered)}

 /* istanbul ignore next */ if(typeof document!=='undefined')document.addEventListener('DOMContentLoaded',function(){renderTable()});

 /* istanbul ignore next */ if(typeof module!=='undefined'&&module.exports)module.exports={ELEMENTS,CAT_COLORS,renderTable,showDetail,filterElements};
