
  function getGradient(c1,c2,c3,angle,type){if(type==='radial')return'radial-gradient(circle,'+c1+','+c2+','+c3+')';return'linear-gradient('+angle+'deg,'+c1+','+c2+','+c3+')'}

  function updatePreview(){if(typeof document==='undefined')return;const c1=document.getElementById('c1');const c2=document.getElementById('c2');const c3=document.getElementById('c3');const angle=document.getElementById('angle');const gtype=document.getElementById('gtype');const p=document.getElementById('preview');if(p)p.style.backgroundImage=getGradient(c1?c1.value:'#6366f1',c2?c2.value:'#ec4899',c3?c3.value:'#06b6d4',angle?angle.value:135,gtype?gtype.value:'linear');const av=document.getElementById('angle-val');if(av&&angle)av.textContent=angle.value+'°'}

  function exportWallpaper(){if(typeof document==='undefined')return;const resEl=document.getElementById('res');const res=(resEl?resEl.value:'1920x1080').split('x').map(Number);const canvas=document.createElement('canvas');canvas.width=res[0];canvas.height=res[1];const ctx=canvas.getContext('2d');const c1=document.getElementById('c1');const c2=document.getElementById('c2');const c3=document.getElementById('c3');const angleEl=document.getElementById('angle');const angle=(parseInt(angleEl?angleEl.value:135))*Math.PI/180;const gtypeEl=document.getElementById('gtype');let grad;if((gtypeEl?gtypeEl.value:'linear')==='radial'){grad=ctx.createRadialGradient(res[0]/2,res[1]/2,0,res[0]/2,res[1]/2,Math.max(res[0],res[1])/2)}else{grad=ctx.createLinearGradient(res[0]/2-Math.cos(angle)*res[0],res[1]/2-Math.sin(angle)*res[1],res[0]/2+Math.cos(angle)*res[0],res[1]/2+Math.sin(angle)*res[1])}grad.addColorStop(0,c1?c1.value:'#6366f1');grad.addColorStop(.5,c2?c2.value:'#ec4899');grad.addColorStop(1,c3?c3.value:'#06b6d4');ctx.fillStyle=grad;ctx.fillRect(0,0,res[0],res[1]);canvas.toBlob(function(b){if(!b)return;const u=URL.createObjectURL(b);const a=document.createElement('a');a.href=u;a.download='wallpaper.png';a.click();URL.revokeObjectURL(u)})}

 function init(){if(typeof document==='undefined')return;document.getElementById('app').innerHTML='<div class="card glass"><div style="display:flex;gap:12px;flex-wrap:wrap"><div><label class="label">Color 1</label><input type="color" id="c1" value="#6366f1" oninput="updatePreview()"></div><div><label class="label">Color 2</label><input type="color" id="c2" value="#ec4899" oninput="updatePreview()"></div><div><label class="label">Color 3</label><input type="color" id="c3" value="#06b6d4" oninput="updatePreview()"></div><div><label class="label">Angle</label><input type="range" id="angle" min="0" max="360" value="135" oninput="updatePreview()"> <span id="angle-val">135°</span></div><div><label class="label">Type</label><select id="gtype" class="input" onchange="updatePreview()"><option>linear</option><option>radial</option></select></div></div><div id="preview" style="width:100%;height:300px;border:2px solid var(--color-border);margin-top:16px"></div><div style="display:flex;gap:12px;margin-top:16px"><select id="res" class="input"><option value="1920x1080">Desktop</option><option value="1080x1920">Phone</option><option value="2560x1440">2K</option><option value="3840x2160">4K</option></select><button class="btn btn-primary" onclick="exportWallpaper()">📥 Download PNG</button></div></div>';updatePreview()}

 if(typeof document!=='undefined')document.addEventListener('DOMContentLoaded',init);

 if(typeof module!=='undefined'&&module.exports)module.exports={getGradient,updatePreview,exportWallpaper,init};
