let habits=[];function loadHabits(){try{habits=JSON.parse(localStorage.getItem('habits')||'[]')}catch(e){habits=[]}}
function saveHabits(){try{localStorage.setItem('habits',JSON.stringify(habits))}catch(e){}}
function addHabit(name){if(typeof document!=='undefined'&&!name){const i=document.getElementById('habit-input');name=i?i.value.trim():'';if(i)i.value=''}if(!name)return;habits.push({id:Date.now(),name,log:{},streak:0});saveHabits();render()}
function removeHabit(id){habits=habits.filter(h=>h.id!==id);saveHabits();render()}
function toggleToday(id){const h=habits.find(x=>x.id===id);if(!h)return;const today=new Date().toISOString().slice(0,10);h.log[today]=!h.log[today];h.streak=calcStreak(h.log);saveHabits();render()}
function calcStreak(log){let s=0;const d=new Date();for(let i=0;i<365;i++){const key=new Date(d-i*864e5).toISOString().slice(0,10);if(log[key])s++;else break}return s}
function render(){if(typeof document==='undefined')return;const el=document.getElementById('habits');if(!el)return;const today=new Date().toISOString().slice(0,10);el.innerHTML=habits.map(h=>'<div class="habit-row"><button class="check-btn'+(h.log[today]?' done':'')+'" onclick="toggleToday('+h.id+')">'+(h.log[today]?'✓':'')+'</button><span class="habit-name">'+h.name+'</span><span class="streak">🔥 '+h.streak+'</span><button class="del-btn" onclick="removeHabit('+h.id+')">✕</button></div>').join('');renderHeatmap()}
function renderHeatmap(){if(typeof document==='undefined')return;const el=document.getElementById('heatmap');if(!el)return;let html='';for(let i=29;i>=0;i--){const d=new Date(Date.now()-i*864e5).toISOString().slice(0,10);let count=0;habits.forEach(h=>{if(h.log[d])count++});const lvl=count===0?'':count<=1?' hm-1':count<=2?' hm-2':count<=3?' hm-3':' hm-4';html+='<div class="hm-cell'+lvl+'" title="'+d+': '+count+'"></div>'}el.innerHTML=html}
if(typeof document!=='undefined')document.addEventListener('DOMContentLoaded',()=>{loadHabits();render()});
if(typeof module!=='undefined'&&module.exports)module.exports={addHabit,removeHabit,toggleToday,calcStreak,render,renderHeatmap,loadHabits,saveHabits,getHabits:()=>habits,setHabits:h=>{habits=h}};