var cities=[];var tickInterval=null;
function loadCities(){try{cities=JSON.parse(localStorage.getItem('worldClockCities')||'[]')}catch(e){}if(!cities.length)cities=['America/New_York','Europe/London','Asia/Tokyo','Asia/Kolkata']}
function saveCities(){try{localStorage.setItem('worldClockCities',JSON.stringify(cities))}catch(e){}}
function addCity(tz){if(typeof document!=='undefined'&&!tz){var sel=document.getElementById('city-select');tz=sel?sel.value:'UTC'}if(!tz||cities.indexOf(tz)!==-1)return;cities.push(tz);saveCities();renderClocks()}
function removeCity(tz){cities=cities.filter(function(c){return c!==tz});saveCities();renderClocks()}
function getCityName(tz){return tz.split('/').pop().replace(/_/g,' ')}
function getTimeInTZ(tz){try{return new Date().toLocaleTimeString('en-US',{timeZone:tz,hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:true})}catch(e){return'--:--:--'}}
function getDateInTZ(tz){try{return new Date().toLocaleDateString('en-US',{timeZone:tz,weekday:'short',month:'short',day:'numeric'})}catch(e){return''}}
function isDay(tz){try{var h=parseInt(new Date().toLocaleString('en-US',{timeZone:tz,hour:'numeric',hour12:false}));return h>=6&&h<18}catch(e){return true}}
function renderClocks(){if(typeof document==='undefined')return;var el=document.getElementById('clocks');if(!el)return;el.innerHTML=cities.map(function(tz){var day=isDay(tz);return'<div style="padding:20px;text-align:center;background:var(--color-surface-alt);border-radius:12px;border:1px solid var(--color-border);position:relative"><button style="position:absolute;top:8px;right:8px;background:none;border:none;color:#ef4444;cursor:pointer" onclick="removeCity(\''+tz+'\')">✕</button><div style="font-weight:700;font-size:1.1rem;margin-bottom:8px"><span style="display:inline-block;width:10px;height:10px;border-radius:50%;margin-right:6px;background:'+(day?'#facc15':'#6366f1')+'"></span>'+getCityName(tz)+'</div><div style="font-size:2rem;font-weight:800;font-family:monospace;background:linear-gradient(135deg,var(--color-primary),var(--color-accent));-webkit-background-clip:text;-webkit-text-fill-color:transparent">'+getTimeInTZ(tz)+'</div><div style="font-size:.8rem;color:var(--color-text-secondary);margin-top:4px">'+getDateInTZ(tz)+'</div></div>'}).join('')}
function init(){if(typeof document==='undefined')return;document.getElementById('app').innerHTML='<div class="card"><div style="display:flex;gap:12px;margin-bottom:16px"><select id="city-select" class="input" style="flex:1"><option value="America/New_York">New York</option><option value="America/Los_Angeles">Los Angeles</option><option value="Europe/London">London</option><option value="Europe/Paris">Paris</option><option value="Asia/Tokyo">Tokyo</option><option value="Asia/Shanghai">Shanghai</option><option value="Asia/Kolkata">Mumbai</option><option value="Asia/Dubai">Dubai</option><option value="Australia/Sydney">Sydney</option></select><button class="btn btn-primary" onclick="addCity()">Add</button></div><div id="clocks" style="display:grid;grid-template-columns:repeat(auto-fill,minmax(200px,1fr));gap:12px"></div></div>';loadCities();renderClocks();clearInterval(tickInterval);tickInterval=setInterval(renderClocks,1000)}
if(typeof document!=='undefined')document.addEventListener('DOMContentLoaded',init);
if(typeof module!=='undefined'&&module.exports)module.exports={addCity,removeCity,getCityName,getTimeInTZ,getDateInTZ,isDay,renderClocks,loadCities,saveCities,init,getCities:function(){return cities},setCities:function(c){cities=c}};
